### ISSUE TITLE
Watcher keep crashing because of permission issue

### ISSUE THREAD

**Issue by Sebclem** [bpereto/borg-hive#49]
Hi,

My watcher keep crashing as soon as i init at repo, it caused by a permission issue :

```
watcher_1  | PermissionError: [Errno 13] Permission denied: '/repos/2fl9gc41/docker'
```

It seams that borg init the repo with this permission : 
```
drwx------ 3 1114 1000 4.0K Apr 13 15:07 docker/
```
So the watcher can't read it

**Comment by Sebclem** [comment]
it's seams to be the same issue as #19, but not fixed for me ?

**Comment by Sebclem** [comment]
I have found a workaround : adding `--umask 0007` to the borg init command.

With borgmatic, you can add this in the config file with:
```yml
storage:
  extra_borg_options:
    # Extra command-line options to pass to "borg init".
    init: --umask 0007
```
