### ISSUE TITLE
SSH keys permission denied

### ISSUE THREAD

**Issue by Firesphere** [bpereto/borg-hive#76]
As of 8th of November, all my clients are getting a `Permission denied (publickey).` from their keys.

Any idea what could cause this?

**Comment by Firesphere** [comment]
All I can think of, is possibly an update executed?
Here's my update log:
```
Start-Date: 2022-11-08  06:18:10
Commandline: /usr/bin/unattended-upgrade
Upgrade: libsqlite3-0:amd64 (3.37.2-2, 3.37.2-2ubuntu0.1)
End-Date: 2022-11-08  06:18:13

Start-Date: 2022-11-08  06:51:13
Commandline: apt dist-upgrade -y
Requested-By: ubuntu (1001)
Upgrade: libtiff5:amd64 (4.3.0-6ubuntu0.1, 4.3.0-6ubuntu0.2), distro-info-data:amd64 (0.52ubuntu0.1, 0.52ubuntu0.2)
End-Date: 2022-11-08  06:51:14

Start-Date: 2022-11-08  09:44:34
Requested-By: ubuntu (1001)
Upgrade: grub-efi-amd64-signed:amd64 (1.180+2.06-2ubuntu7, 1.182~22.04.1+2.06-2ubuntu10), grub-efi-amd64-bin:amd64 (2.06-2ubuntu7, 2.06-2ubuntu10), ubuntu-advantage-tools:amd64 (27.11.2~22.04.1, 27.11.3~22.04.1)
End-Date: 2022-11-08  09:44:58
```

**Comment by r3c4ll** [comment]
Hi @Firesphere, did you solve this issue?

**Comment by bpereto** [comment]
Sorry for the long time to reply.

it's not clear, how your setup is. But the configuration (ssh) in the container should not change.
I must test this - have you the docker compose setup?

**Comment by Firesphere** [comment]
I got it solved by giving the Borg container full networking privilege, so that it would accept any port to forward to 2222.

I don't know _why_ it needed to be able to take any port, but it seems to have solved the issue for now. It's not an ideal one though.

This is my Docker Compose:
```
version: '3'
services:
  db:
    image: mariadb:latest
    container_name: "MariaDB"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file:
      - .env
    labels:
      - "diun.enable=true"
    restart: always
  app:
    image: bpereto/borg-hive:0.1.3
    container_name: "BorgApp"
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:/repos
      - static:/staticfiles
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    labels:
      - "diun.enable=true"
    restart: always
  worker:
    image: bpereto/borg-hive:0.1.3
    container_name: "BorgWorker"
    entrypoint: celery -A core worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:/repos:ro
    depends_on:
      - db
    labels:
      - "diun.enable=true"
    restart: always
  watcher:
    image: bpereto/borg-hive:0.1.3
    container_name: "BorgWatcher"
    entrypoint: /bin/bash -c "/app/manage.py watch_repositories"
    env_file:
      - .env
    volumes:
      - borg-repos:/repos:ro
    depends_on:
      - db
    restart: 'on-failure'

  borg:
    image: bpereto/borg-hive:borg-0.1.3
    container_name: "Borg"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - borg-repos:/repos
      - borg-config:/config
    ports:
      - "${BORG_SSH_PORT}:22"
    restart: always

  ldap:
    image: osixia/openldap-backup:latest
    container_name: "LDAP"
    env_file:
      - .env
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ldap-backup:/data/backup
    restart: always
  redis:
    image: redis:latest
    container_name: "Redis"
    labels:
      - "diun.enable=true"
    restart: always

  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - /home/ubuntu/docker/diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/docker/diun/diun.yml:/diun.yml:ro
    environment:
      - "TZ=Pacific/Auckland"
      - "LOG_LEVEL=warn"
      - "LOG_JSON=false"
    labels:
      - "diun.enable=true"
    restart: always
        
volumes:
  mariadb-data:
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/docker/mariadb/data
  mariadb-conf:
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/docker/mariadb/mariadb.conf.d
  ldap-data:
  ldap-config:
  borg-config:
  static:
  borg-repos:
    driver_opts:
      type: none
      o: bind
      device: /mnt/blockstorage/backups
  ldap-backup:
    driver_opts:
      type: none
      o: bind
      device: /mnt/blockstorage/ldap
```
